# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.verify_auditor_credentials_request import VerifyAuditorCredentialsRequest

class TestVerifyAuditorCredentialsRequest(unittest.TestCase):
    """VerifyAuditorCredentialsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyAuditorCredentialsRequest:
        """Test VerifyAuditorCredentialsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyAuditorCredentialsRequest`
        """
        model = VerifyAuditorCredentialsRequest()
        if include_optional:
            return VerifyAuditorCredentialsRequest(
                document_url = '',
                credential_type = 'ROAC',
                organization_id = ''
            )
        else:
            return VerifyAuditorCredentialsRequest(
                document_url = '',
        )
        """

    def testVerifyAuditorCredentialsRequest(self):
        """Test VerifyAuditorCredentialsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
