# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.code_execution_request import CodeExecutionRequest

class TestCodeExecutionRequest(unittest.TestCase):
    """CodeExecutionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodeExecutionRequest:
        """Test CodeExecutionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodeExecutionRequest`
        """
        model = CodeExecutionRequest()
        if include_optional:
            return CodeExecutionRequest(
                code = '',
                language = 'python',
                context = {
                    'key' : null
                    },
                dependencies = [
                    ''
                    ]
            )
        else:
            return CodeExecutionRequest(
                code = '',
        )
        """

    def testCodeExecutionRequest(self):
        """Test CodeExecutionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
