# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.verify_auditor_credentials_response import VerifyAuditorCredentialsResponse

class TestVerifyAuditorCredentialsResponse(unittest.TestCase):
    """VerifyAuditorCredentialsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyAuditorCredentialsResponse:
        """Test VerifyAuditorCredentialsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyAuditorCredentialsResponse`
        """
        model = VerifyAuditorCredentialsResponse()
        if include_optional:
            return VerifyAuditorCredentialsResponse(
                auditor_profile_id = '',
                credential_type = '',
                verified = True,
                credential_number = '',
                verification_date = '',
                valid_until = '',
                details = {
                    'key' : null
                    },
                error_message = ''
            )
        else:
            return VerifyAuditorCredentialsResponse(
                auditor_profile_id = '',
                credential_type = '',
                verified = True,
        )
        """

    def testVerifyAuditorCredentialsResponse(self):
        """Test VerifyAuditorCredentialsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
