# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.refresh_input import RefreshInput

class TestRefreshInput(unittest.TestCase):
    """RefreshInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefreshInput:
        """Test RefreshInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefreshInput`
        """
        model = RefreshInput()
        if include_optional:
            return RefreshInput(
                refresh_token = ''
            )
        else:
            return RefreshInput(
                refresh_token = '',
        )
        """

    def testRefreshInput(self):
        """Test RefreshInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
