# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.autoaudit_interfaces_api_v1_agents_agent_response import AutoauditInterfacesApiV1AgentsAgentResponse

class TestAutoauditInterfacesApiV1AgentsAgentResponse(unittest.TestCase):
    """AutoauditInterfacesApiV1AgentsAgentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoauditInterfacesApiV1AgentsAgentResponse:
        """Test AutoauditInterfacesApiV1AgentsAgentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoauditInterfacesApiV1AgentsAgentResponse`
        """
        model = AutoauditInterfacesApiV1AgentsAgentResponse()
        if include_optional:
            return AutoauditInterfacesApiV1AgentsAgentResponse(
                id = '',
                name = '',
                description = '',
                status = '',
                agent_type = '',
                model_id = '',
                owner_id = '',
                project_id = '',
                tools = [
                    {
                        'key' : null
                        }
                    ],
                created_at = '',
                updated_at = '',
                last_active = ''
            )
        else:
            return AutoauditInterfacesApiV1AgentsAgentResponse(
                id = '',
                name = '',
                status = '',
                agent_type = '',
                model_id = '',
                owner_id = '',
                created_at = '',
                updated_at = '',
        )
        """

    def testAutoauditInterfacesApiV1AgentsAgentResponse(self):
        """Test AutoauditInterfacesApiV1AgentsAgentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
