# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.api.sandbox_api import SandboxApi


class TestSandboxApi(unittest.TestCase):
    """SandboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SandboxApi()

    def tearDown(self) -> None:
        pass

    def test_execute_code_sandbox_execute_post(self) -> None:
        """Test case for execute_code_sandbox_execute_post

        Execute Code
        """
        pass

    def test_health_check_sandbox_health_get(self) -> None:
        """Test case for health_check_sandbox_health_get

        Health Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
