# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.workflow_response import WorkflowResponse

class TestWorkflowResponse(unittest.TestCase):
    """WorkflowResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowResponse:
        """Test WorkflowResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowResponse`
        """
        model = WorkflowResponse()
        if include_optional:
            return WorkflowResponse(
                id = '',
                name = '',
                description = '',
                version = '',
                owner_id = '',
                is_public = True,
                tags = [
                    ''
                    ],
                created_at = '',
                updated_at = '',
                nodes_count = 56,
                edges_count = 56
            )
        else:
            return WorkflowResponse(
                id = '',
                name = '',
                description = '',
                version = '',
                owner_id = '',
                is_public = True,
                tags = [
                    ''
                    ],
                created_at = '',
                updated_at = '',
                nodes_count = 56,
                edges_count = 56,
        )
        """

    def testWorkflowResponse(self):
        """Test WorkflowResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
