# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.code_execution_response import CodeExecutionResponse

class TestCodeExecutionResponse(unittest.TestCase):
    """CodeExecutionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodeExecutionResponse:
        """Test CodeExecutionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodeExecutionResponse`
        """
        model = CodeExecutionResponse()
        if include_optional:
            return CodeExecutionResponse(
                status = '',
                stdout = '',
                stderr = '',
                execution_time = 1.337,
                exit_code = 56
            )
        else:
            return CodeExecutionResponse(
                status = '',
                stdout = '',
                stderr = '',
                execution_time = 1.337,
        )
        """

    def testCodeExecutionResponse(self):
        """Test CodeExecutionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
