# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.api.superagents_api import SuperagentsApi


class TestSuperagentsApi(unittest.TestCase):
    """SuperagentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuperagentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent_api_v1_superagents_post(self) -> None:
        """Test case for create_agent_api_v1_superagents_post

        Create Agent
        """
        pass

    def test_delete_agent_api_v1_superagents_agent_id_delete(self) -> None:
        """Test case for delete_agent_api_v1_superagents_agent_id_delete

        Delete Agent
        """
        pass

    def test_get_agent_api_v1_superagents_agent_id_get(self) -> None:
        """Test case for get_agent_api_v1_superagents_agent_id_get

        Get Agent
        """
        pass

    def test_list_agents_api_v1_superagents_get(self) -> None:
        """Test case for list_agents_api_v1_superagents_get

        List Agents
        """
        pass

    def test_update_agent_api_v1_superagents_agent_id_patch(self) -> None:
        """Test case for update_agent_api_v1_superagents_agent_id_patch

        Update Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
