# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.api.marketplace_api import MarketplaceApi


class TestMarketplaceApi(unittest.TestCase):
    """MarketplaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketplaceApi()

    def tearDown(self) -> None:
        pass

    def test_monitor_placsp_tenders_api_v1_marketplace_placsp_monitor_post(self) -> None:
        """Test case for monitor_placsp_tenders_api_v1_marketplace_placsp_monitor_post

        Monitor PLACSP for new tenders
        """
        pass

    def test_verify_auditor_credentials_api_v1_marketplace_auditor_profiles_auditor_profile_id_verify_credentials_post(self) -> None:
        """Test case for verify_auditor_credentials_api_v1_marketplace_auditor_profiles_auditor_profile_id_verify_credentials_post

        Verify auditor credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
