# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.document_response import DocumentResponse

class TestDocumentResponse(unittest.TestCase):
    """DocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentResponse:
        """Test DocumentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentResponse`
        """
        model = DocumentResponse()
        if include_optional:
            return DocumentResponse(
                id = '',
                name = '',
                description = '',
                document_type = '',
                status = '',
                file_path = '',
                file_type = '',
                file_size = 56,
                created_at = '',
                updated_at = '',
                processed_at = '',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return DocumentResponse(
                id = '',
                name = '',
                document_type = '',
                status = '',
        )
        """

    def testDocumentResponse(self):
        """Test DocumentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
