# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_get_google_oauth_url_api_v1_oauth_google_get(self) -> None:
        """Test case for get_google_oauth_url_api_v1_oauth_google_get

        Get Google Oauth Url
        """
        pass

    def test_get_microsoft_oauth_url_api_v1_oauth_microsoft_get(self) -> None:
        """Test case for get_microsoft_oauth_url_api_v1_oauth_microsoft_get

        Get Microsoft Oauth Url
        """
        pass

    def test_get_user_info_api_v1_auth_me_get(self) -> None:
        """Test case for get_user_info_api_v1_auth_me_get

        Get User Info
        """
        pass

    def test_google_callback_api_v1_v1_auth_callback_google_get(self) -> None:
        """Test case for google_callback_api_v1_v1_auth_callback_google_get

        Google Callback
        """
        pass

    def test_google_post_callback_api_v1_v1_auth_callback_google_post(self) -> None:
        """Test case for google_post_callback_api_v1_v1_auth_callback_google_post

        Google Post Callback
        """
        pass

    def test_login_api_v1_auth_login_post(self) -> None:
        """Test case for login_api_v1_auth_login_post

        Login
        """
        pass

    def test_login_for_access_token_api_v1_auth_token_post(self) -> None:
        """Test case for login_for_access_token_api_v1_auth_token_post

        Login For Access Token
        """
        pass

    def test_microsoft_callback_api_v1_v1_auth_callback_microsoft_get(self) -> None:
        """Test case for microsoft_callback_api_v1_v1_auth_callback_microsoft_get

        Microsoft Callback
        """
        pass

    def test_microsoft_post_callback_api_v1_v1_auth_callback_microsoft_post(self) -> None:
        """Test case for microsoft_post_callback_api_v1_v1_auth_callback_microsoft_post

        Microsoft Post Callback
        """
        pass

    def test_oauth_authorize_api_v1_auth_oauth_provider_get(self) -> None:
        """Test case for oauth_authorize_api_v1_auth_oauth_provider_get

        Oauth Authorize
        """
        pass

    def test_oauth_login_api_v1_auth_oauth_post(self) -> None:
        """Test case for oauth_login_api_v1_auth_oauth_post

        Oauth Login
        """
        pass

    def test_refresh_access_token_api_v1_auth_refresh_post(self) -> None:
        """Test case for refresh_access_token_api_v1_auth_refresh_post

        Refresh Access Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
