# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.update_agent_request import UpdateAgentRequest

class TestUpdateAgentRequest(unittest.TestCase):
    """UpdateAgentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAgentRequest:
        """Test UpdateAgentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAgentRequest`
        """
        model = UpdateAgentRequest()
        if include_optional:
            return UpdateAgentRequest(
                name = '',
                description = '',
                capabilities = [
                    autoaudit.models.agent_capability_request.AgentCapabilityRequest(
                        name = '', 
                        description = '', 
                        parameters = {
                            'key' : null
                            }, 
                        category = 'general', 
                        execution_tier = 'standard', )
                    ],
                tools = [
                    autoaudit.models.agent_tool_request.AgentToolRequest(
                        tool_id = '', 
                        parameters = {
                            'key' : null
                            }, )
                    ],
                llm_id = '',
                metadata = {
                    'key' : null
                    },
                execution_tier = '',
                max_iterations = 56,
                status = 'active'
            )
        else:
            return UpdateAgentRequest(
        )
        """

    def testUpdateAgentRequest(self):
        """Test UpdateAgentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
