# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.agent_status import AgentStatus

class TestAgentStatus(unittest.TestCase):
    """AgentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentStatus(self):
        """Test AgentStatus"""
        # inst = AgentStatus()

if __name__ == '__main__':
    unittest.main()
