# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.project_create_from_template_request import ProjectCreateFromTemplateRequest

class TestProjectCreateFromTemplateRequest(unittest.TestCase):
    """ProjectCreateFromTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreateFromTemplateRequest:
        """Test ProjectCreateFromTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCreateFromTemplateRequest`
        """
        model = ProjectCreateFromTemplateRequest()
        if include_optional:
            return ProjectCreateFromTemplateRequest(
                name = '',
                template_id = '',
                organization_id = '',
                description = '',
                settings = {
                    'key' : null
                    }
            )
        else:
            return ProjectCreateFromTemplateRequest(
                name = '',
                template_id = '',
                organization_id = '',
        )
        """

    def testProjectCreateFromTemplateRequest(self):
        """Test ProjectCreateFromTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
