# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.monitor_placsp_tenders_response import MonitorPLACSPTendersResponse

class TestMonitorPLACSPTendersResponse(unittest.TestCase):
    """MonitorPLACSPTendersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorPLACSPTendersResponse:
        """Test MonitorPLACSPTendersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorPLACSPTendersResponse`
        """
        model = MonitorPLACSPTendersResponse()
        if include_optional:
            return MonitorPLACSPTendersResponse(
                organization_id = '',
                total_tenders = 56,
                tenders = [
                    {
                        'key' : null
                        }
                    ],
                search_criteria = {
                    'key' : null
                    },
                search_timestamp = '',
                error_message = ''
            )
        else:
            return MonitorPLACSPTendersResponse(
                organization_id = '',
                total_tenders = 56,
                tenders = [
                    {
                        'key' : null
                        }
                    ],
                search_criteria = {
                    'key' : null
                    },
                search_timestamp = '',
        )
        """

    def testMonitorPLACSPTendersResponse(self):
        """Test MonitorPLACSPTendersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
