# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.api.documents_api import DocumentsApi


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_document_schema_api_v1_documents_schema_post(self) -> None:
        """Test case for create_document_schema_api_v1_documents_schema_post

        Create Document Schema
        """
        pass

    def test_get_document_api_v1_documents_document_id_get(self) -> None:
        """Test case for get_document_api_v1_documents_document_id_get

        Get Document
        """
        pass

    def test_get_document_content_api_v1_documents_document_id_content_get(self) -> None:
        """Test case for get_document_content_api_v1_documents_document_id_content_get

        Get Document Content
        """
        pass

    def test_search_documents_api_v1_documents_get(self) -> None:
        """Test case for search_documents_api_v1_documents_get

        Search Documents
        """
        pass

    def test_update_document_api_v1_documents_document_id_patch(self) -> None:
        """Test case for update_document_api_v1_documents_document_id_patch

        Update Document
        """
        pass


if __name__ == '__main__':
    unittest.main()
