# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.models.autoaudit_interfaces_api_v1_agents_create_agent_request import AutoauditInterfacesApiV1AgentsCreateAgentRequest

class TestAutoauditInterfacesApiV1AgentsCreateAgentRequest(unittest.TestCase):
    """AutoauditInterfacesApiV1AgentsCreateAgentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoauditInterfacesApiV1AgentsCreateAgentRequest:
        """Test AutoauditInterfacesApiV1AgentsCreateAgentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoauditInterfacesApiV1AgentsCreateAgentRequest`
        """
        model = AutoauditInterfacesApiV1AgentsCreateAgentRequest()
        if include_optional:
            return AutoauditInterfacesApiV1AgentsCreateAgentRequest(
                name = '',
                description = '',
                model_id = '',
                agent_type = '',
                project_id = '',
                selected_capabilities = [
                    ''
                    ],
                config = {
                    'key' : null
                    }
            )
        else:
            return AutoauditInterfacesApiV1AgentsCreateAgentRequest(
                name = '',
                description = '',
                model_id = '',
                agent_type = '',
        )
        """

    def testAutoauditInterfacesApiV1AgentsCreateAgentRequest(self):
        """Test AutoauditInterfacesApiV1AgentsCreateAgentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
