# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoaudit.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_activate_agent_api_v1_agents_agent_id_activate_post(self) -> None:
        """Test case for activate_agent_api_v1_agents_agent_id_activate_post

        Activate Agent
        """
        pass

    def test_create_agent_api_v1_agents_post(self) -> None:
        """Test case for create_agent_api_v1_agents_post

        Create Agent
        """
        pass

    def test_create_workflow_with_agent_api_v1_agents_agent_id_create_workflow_post(self) -> None:
        """Test case for create_workflow_with_agent_api_v1_agents_agent_id_create_workflow_post

        Create Workflow With Agent
        """
        pass

    def test_execute_agent_command_api_v1_agents_agent_id_command_post(self) -> None:
        """Test case for execute_agent_command_api_v1_agents_agent_id_command_post

        Execute Agent Command
        """
        pass

    def test_get_agent_api_v1_agents_agent_id_get(self) -> None:
        """Test case for get_agent_api_v1_agents_agent_id_get

        Get Agent
        """
        pass

    def test_list_agents_api_v1_agents_get(self) -> None:
        """Test case for list_agents_api_v1_agents_get

        List Agents
        """
        pass


if __name__ == '__main__':
    unittest.main()
