# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AgentStatus(str, Enum):
    """
    Status of an agent
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    INACTIVE = 'inactive'
    SUSPENDED = 'suspended'
    DELETED = 'deleted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AgentStatus from a JSON string"""
        return cls(json.loads(json_str))


