# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AutoauditInterfacesApiV1AgentsAgentResponse(BaseModel):
    """
    Response model for agents
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    description: Optional[StrictStr] = None
    status: StrictStr
    agent_type: StrictStr
    model_id: StrictStr
    owner_id: StrictStr
    project_id: Optional[StrictStr] = None
    tools: Optional[List[Dict[str, Any]]] = None
    created_at: StrictStr
    updated_at: StrictStr
    last_active: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "status", "agent_type", "model_id", "owner_id", "project_id", "tools", "created_at", "updated_at", "last_active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoauditInterfacesApiV1AgentsAgentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if last_active (nullable) is None
        # and model_fields_set contains the field
        if self.last_active is None and "last_active" in self.model_fields_set:
            _dict['last_active'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoauditInterfacesApiV1AgentsAgentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "agent_type": obj.get("agent_type"),
            "model_id": obj.get("model_id"),
            "owner_id": obj.get("owner_id"),
            "project_id": obj.get("project_id"),
            "tools": obj.get("tools"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "last_active": obj.get("last_active")
        })
        return _obj


