# coding: utf-8

"""
    AutoAudit API

    API for AutoAudit

    The version of the OpenAPI document: 1.0.0
    Contact: support@autoaudit.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class VerifyAuditorCredentialsResponse(BaseModel):
    """
    Response model for auditor credential verification.
    """ # noqa: E501
    auditor_profile_id: StrictStr
    credential_type: StrictStr
    verified: StrictBool
    credential_number: Optional[StrictStr] = None
    verification_date: Optional[StrictStr] = None
    valid_until: Optional[StrictStr] = None
    details: Optional[Dict[str, Any]] = None
    error_message: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["auditor_profile_id", "credential_type", "verified", "credential_number", "verification_date", "valid_until", "details", "error_message"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VerifyAuditorCredentialsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if credential_number (nullable) is None
        # and model_fields_set contains the field
        if self.credential_number is None and "credential_number" in self.model_fields_set:
            _dict['credential_number'] = None

        # set to None if verification_date (nullable) is None
        # and model_fields_set contains the field
        if self.verification_date is None and "verification_date" in self.model_fields_set:
            _dict['verification_date'] = None

        # set to None if valid_until (nullable) is None
        # and model_fields_set contains the field
        if self.valid_until is None and "valid_until" in self.model_fields_set:
            _dict['valid_until'] = None

        # set to None if details (nullable) is None
        # and model_fields_set contains the field
        if self.details is None and "details" in self.model_fields_set:
            _dict['details'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VerifyAuditorCredentialsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auditor_profile_id": obj.get("auditor_profile_id"),
            "credential_type": obj.get("credential_type"),
            "verified": obj.get("verified"),
            "credential_number": obj.get("credential_number"),
            "verification_date": obj.get("verification_date"),
            "valid_until": obj.get("valid_until"),
            "details": obj.get("details"),
            "error_message": obj.get("error_message")
        })
        return _obj


